### ISSUE TITLE
multi-views for documents/entities dense retrieval

### ISSUE THREAD

**Issue by PaulLerner** [laura-dietz/neurosymbolic-representations-for-IR#1]
Here are the papers I mentioned:
- https://aclanthology.org/2022.acl-long.414
- https://aclanthology.org/2022.acl-long.76

**Comment by laura-dietz** [comment]
Thanks, Paul. I will pass those along.

Thank you for participating, I did appreciate your insight.

Laura

**Comment by PaulLerner** [comment]
Thanks for organizing, it was great!
